// ------------------------------------------------------------------------------
//  <auto-generated>
//      Ce code a été généré par un générateur de test codé de l'interface utilisateur.
//      Version : 12.0.0.0 
//
//      Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//      le code est régénéré.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIFileEprojetvisualstuWindow.UIFileEprojetvisualstuTitleBar.UICloseButton;
            #endregion

            // Clic 'Close' bouton
            Mouse.Click(uICloseButton, new Point(19, 10));
        }
        
        #region Properties
        public UIFileEprojetvisualstuWindow UIFileEprojetvisualstuWindow
        {
            get
            {
                if ((this.mUIFileEprojetvisualstuWindow == null))
                {
                    this.mUIFileEprojetvisualstuWindow = new UIFileEprojetvisualstuWindow();
                }
                return this.mUIFileEprojetvisualstuWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFileEprojetvisualstuWindow mUIFileEprojetvisualstuWindow;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.31101.0")]
    public class UIFileEprojetvisualstuWindow : WinWindow
    {
        
        public UIFileEprojetvisualstuWindow()
        {
            #region Critères de recherche 
            this.SearchProperties[WinWindow.PropertyNames.Name] = "file:///E:/projet visual studio/CodinGame/Clone-TailleduCode/Super Calculateur/bi" +
                "n/Debug/Super Calculateur.EXE";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ConsoleWindowClass";
            this.WindowTitles.Add("file:///E:/projet visual studio/CodinGame/Clone-TailleduCode/Super Calculateur/bi" +
                    "n/Debug/Super Calculateur.EXE");
            #endregion
        }
        
        #region Properties
        public UIFileEprojetvisualstuTitleBar UIFileEprojetvisualstuTitleBar
        {
            get
            {
                if ((this.mUIFileEprojetvisualstuTitleBar == null))
                {
                    this.mUIFileEprojetvisualstuTitleBar = new UIFileEprojetvisualstuTitleBar(this);
                }
                return this.mUIFileEprojetvisualstuTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIFileEprojetvisualstuTitleBar mUIFileEprojetvisualstuTitleBar;
        #endregion
    }
    
    [GeneratedCode("Générateur de test codé de l\'interface utilisateur", "12.0.31101.0")]
    public class UIFileEprojetvisualstuTitleBar : WinTitleBar
    {
        
        public UIFileEprojetvisualstuTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Critères de recherche 
            this.WindowTitles.Add("file:///E:/projet visual studio/CodinGame/Clone-TailleduCode/Super Calculateur/bi" +
                    "n/Debug/Super Calculateur.EXE");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Critères de recherche 
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("file:///E:/projet visual studio/CodinGame/Clone-TailleduCode/Super Calculateur/bi" +
                            "n/Debug/Super Calculateur.EXE");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
